version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - 3306:3306
    volumes:
      - ./despliegue-PHP/mysql/01-crearBBDD.sql:/docker-entrypoint-initdb.d/01-crearBBDD.sql
      - ./despliegue-PHP/mysql/02-InsertarDatos.sql:/docker-entrypoint-initdb.d/02-InsertarDatos.sql  
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: dwes
      MYSQL_PASSWORD: dwes
      MYSQL_DATABASE: dwes
    
    networks:
      - app-network

  apache:
    build: apache/
    container_name: apache-app
    depends_on:
      - mysql
    ports:
      - 8080:80
    volumes:
      - ./despliegue-PHP/php/:/var/www/html/
    networks:
      - app-network

  php:
    build: php/
    depends_on:
      - mysql
    ports:
      - 8085:9000
    volumes:
      - ./despliegue-PHP/php/:/var/www/html/
    networks:
      - app-network

  wordpress:
    image: wordpress:latest
    container_name: wordpress-app
    depends_on:
      - mysql
    ports:
      - 8081:80
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-app
    depends_on:
      - mysql
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql
    networks:
      - app-network

networks:
  app-network: